# Generated by Django 5.0.3 on 2026-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_webhook_url", models.URLField(blank=True, null=True)),
                (
                    "telegram_bot_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notify_inactivity", models.BooleanField(default=False)),
                ("notify_chain_drops", models.BooleanField(default=False)),
                ("notify_war_hits", models.BooleanField(default=False)),
            ],
        ),
    ]
