# Generated by Django 5.0.3 on 2026-04-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("torn_faction_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("total_respect", models.IntegerField(default=0)),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("torn_player_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField(default=0)),
                ("faction_rank", models.CharField(max_length=100)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("last_action", models.DateTimeField(blank=True, null=True)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="torn.faction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("hits", models.IntegerField(default=0)),
                (
                    "respect_gain",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("chain_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_logs",
                        to="torn.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("online_status", models.CharField(max_length=50)),
                ("chain_hits", models.IntegerField(default=0)),
                ("respect", models.IntegerField(default=0)),
                ("war_hits", models.IntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="torn.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizedCrime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crime_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("success", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_crimes",
                        to="torn.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("attacks_won", models.IntegerField(default=0)),
                ("attacks_lost", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                (
                    "respect_gain",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="war_logs",
                        to="torn.member",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["torn_player_id"], name="torn_member_torn_pl_c7889c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["faction"], name="torn_member_faction_393681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chainlog",
            index=models.Index(
                fields=["member", "chain_id"], name="torn_chainl_member__a77783_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysnapshot",
            index=models.Index(
                fields=["member", "timestamp"], name="torn_activi_member__5de042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysnapshot",
            index=models.Index(
                fields=["timestamp"], name="torn_activi_timesta_25f6c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizedcrime",
            index=models.Index(
                fields=["member"], name="torn_organi_member__d814d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warlog",
            index=models.Index(
                fields=["member"], name="torn_warlog_member__301c0d_idx"
            ),
        ),
    ]
