# Generated by Django 5.0.3 on 2026-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warlog',
            name='war_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
