# Generated by Django 5.0.3 on 2026-04-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pool', models.DecimalField(decimal_places=2, max_digits=16)),
                ('faction_cut', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payout_mode', models.CharField(choices=[('hits', 'Total Hits'), ('respect', 'Respect Gained')], max_length=20)),
                ('bonus_config', models.JSONField(blank=True, default=dict)),
                ('exclusion_rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('share_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('final_payout', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_excluded', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_distributions', to='torn.member')),
                ('payout_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='leadership.payoutcalculation')),
            ],
            options={
                'ordering': ['-final_payout', 'member__name'],
            },
        ),
        migrations.CreateModel(
            name='ReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('chain_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('war_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('oc_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_level', models.CharField(choices=[('highly_reliable', 'Highly Reliable'), ('stable', 'Stable'), ('at_risk', 'At Risk'), ('high_kick_risk', 'High Kick Risk')], default='high_kick_risk', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_score', to='torn.member')),
            ],
            options={
                'ordering': ['-final_score', 'member__name'],
            },
        ),
        migrations.CreateModel(
            name='ChainAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_slot_time', models.DateTimeField()),
                ('chain_id', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_assignments', to='torn.member')),
            ],
            options={
                'ordering': ['assigned_slot_time'],
                'indexes': [models.Index(fields=['chain_id', 'completed'], name='leadership__chain_i_b010ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChainBreakEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_hit_time', models.DateTimeField(blank=True, null=True)),
                ('expected_next_hit_by', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('chain_broken', models.BooleanField(default=False)),
                ('time_remaining', models.IntegerField(blank=True, null=True)),
                ('last_hitter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slot_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chain_breaks', to='torn.member')),
                ('suspected_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspected_chain_breaks', to='torn.member')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['chain_id', '-timestamp'], name='leadership__chain_i_5dc3c2_idx')],
            },
        ),
    ]
