# Generated by Django 5.0.3 on 2026-04-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('torn', '0002_warlog_war_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedWarPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_id', models.CharField(db_index=True, max_length=64)),
                ('total_pool', models.DecimalField(decimal_places=2, max_digits=16)),
                ('faction_cut', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payout_mode', models.CharField(choices=[('hits', 'Total Hits'), ('respect', 'Total Respect')], max_length=20)),
                ('distributable_pool', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_war_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankedWarPayoutMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hits', models.IntegerField(default=0)),
                ('total_respect', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contribution_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_war_payout_rows', to='torn.member')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leadership.rankedwarpayout')),
            ],
            options={
                'ordering': ['-payout_amount', 'member__name'],
                'unique_together': {('payout', 'member')},
            },
        ),
    ]
